/**
 * Every user-facing string in the product. Nothing is hard-coded in components,
 * so the wording can be reviewed by a clinician in one place — and a second
 * language could be added later without touching the screens.
 */
export const uz = {
  app: {
    name: 'Shifora',
    tagline: 'Diabet bemorlarini shifoxonadan keyin kuzatish tizimi',
    loading: 'Yuklanmoqda...',
    save: 'Saqlash',
    cancel: 'Bekor qilish',
    back: 'Orqaga',
    next: 'Keyingisi',
    close: 'Yopish',
    confirm: 'Tasdiqlash',
    edit: "O'zgartirish",
    add: "Qo'shish",
    remove: "O'chirish",
    search: 'Qidirish',
    all: 'Barchasi',
    yes: 'Ha',
    no: "Yo'q",
    optional: 'ixtiyoriy',
    today: 'Bugun',
    time: 'Vaqt',
    date: 'Sana',
    note: 'Izoh',
    logout: 'Chiqish',
    retry: 'Qayta urinish',
    menu: 'Menyu',
    openMenu: 'Menyuni ochish',
    closeMenu: 'Menyuni yopish',
    errorGeneric: 'Xatolik yuz berdi. Qaytadan urinib ko‘ring.',
    networkError: 'Server bilan bog‘lanib bo‘lmadi.',
    saved: 'Saqlandi',
    notSpecified: 'Belgilanmagan',
  },

  roles: {
    hospital: 'Shifoxona / Tibbiyot xodimi',
    patient: 'Bemor',
    caregiver: 'Bemorning yaqin kishisi',
    nurse: 'Hamshira',
    doctor: 'Shifokor',
    hospital_admin: 'Administrator',
    patientRole: 'Bemor',
    caregiverRole: 'Yaqin kishi',
  },

  login: {
    chooseRole: 'Kim sifatida kirmoqchisiz?',
    chooseRoleHint: 'Kirish uchun o‘zingizga mos bo‘limni tanlang.',
    hospitalDesc: 'Hamshira, shifokor va administrator uchun',
    patientDesc: 'Uydagi davolash rejangizni kuzatish uchun',
    caregiverDesc: 'Yaqiningiz holatini kuzatish uchun',
    title: 'Tizimga kirish',
    phone: 'Telefon raqami',
    phonePlaceholder: '901112233',
    password: 'Parol',
    passwordPlaceholder: 'Parolingizni kiriting',
    submit: 'Kirish',
    submitting: 'Kirilmoqda...',
    changeRole: 'Boshqa bo‘limni tanlash',
    demoTitle: 'Namoyish uchun hisoblar',
    safetyNote:
      'Shifora — klinik qaror qabul qilishni qo‘llab-quvvatlovchi tizim. U tashxis qo‘ymaydi va dori tayinlamaydi.',
  },

  nav: {
    hospital: {
      home: 'Bosh sahifa',
      patients: 'Bemorlar',
      register: "Bemorni ro'yxatdan o'tkazish",
      carePlans: 'Davolash rejalari',
      alerts: 'Ogohlantirishlar',
      questions: 'Javobsiz savollar',
      reports: 'Hisobotlar',
    },
    patient: {
      home: 'Bosh sahifa',
      medications: 'Dorilarim',
      measurements: "O'lchovlarim",
      assistant: 'Hamshira AI',
      alerts: 'Ogohlantirishlar',
      profile: 'Profil',
    },
    caregiver: {
      home: 'Bosh sahifa',
      care: 'Parvarish',
      status: 'Holat',
      alerts: 'Ogohlantirishlar',
      profile: 'Profil',
    },
  },

  status: {
    stable: 'Barqaror',
    attention: "E'tibor kerak",
    urgent: "Shoshilinch ko'rib chiqish",
    urgentShort: 'Shoshilinch',
    label: 'Holat',
    note: 'Bu belgilar tashxis emas — ular kuzatuv jarayonidagi holatni bildiradi.',
  },

  severity: {
    info: "Ma'lumot",
    warning: "E'tibor kerak",
    urgent: "Shoshilinch ko'rib chiqish",
  },

  dashboard: {
    title: 'Bosh sahifa',
    totalPatients: 'Jami bemorlar',
    stable: 'Barqaror',
    attention: "E'tibor talab qiladi",
    urgent: "Shoshilinch ko'rib chiqish",
    importantAlerts: 'Muhim ogohlantirishlar',
    noAlerts: 'Hozircha muhim ogohlantirishlar yo‘q.',
    viewAll: 'Barchasini ko‘rish',
    greeting: 'Xush kelibsiz',
    openAlerts: 'Ochiq ogohlantirishlar',
  },

  patients: {
    title: 'Bemorlar',
    searchPlaceholder: 'Ism yoki telefon raqami bo‘yicha qidirish',
    columns: {
      patient: 'Bemor',
      diabetesType: 'Diabet turi',
      status: 'Holat',
      adherence: 'Dori qabul qilish',
      glucose: 'Glyukoza',
      lastActivity: "So'nggi faollik",
      alert: 'Ogohlantirish',
    },
    empty: 'Bemorlar topilmadi.',
    count: (n: number) => `${n} ta bemor`,
    noData: "Ma'lumot yo'q",
    openProfile: 'Kartani ochish',
  },

  diabetesType: {
    type1: '1-tur',
    type2: '2-tur',
    other: 'Boshqa / aniqlanmagan',
  },

  gender: {
    male: 'Erkak',
    female: 'Ayol',
  },

  register: {
    title: "Bemorni ro'yxatdan o'tkazish",
    steps: {
      patient: "Bemor ma'lumotlari",
      diabetes: 'Diabet haqida',
      medications: 'Dorilar',
      monitoring: 'Kuzatuv rejasi',
      review: 'AI tavsiyasi va tasdiqlash',
    },
    stepOf: (a: number, b: number) => `${a}-qadam / ${b}`,
    firstName: 'Ism',
    lastName: 'Familiya',
    birthDate: "Tug'ilgan sana",
    genderLabel: 'Jins',
    phone: 'Telefon raqami',
    address: 'Manzil',
    emergencyName: 'Favqulodda aloqa shaxsi',
    emergencyPhone: 'Favqulodda aloqa telefoni',
    language: 'Til',
    createAccount: 'Bemor uchun tizimga kirish hisobini yaratish',
    accountHint: 'Bemor telefon raqami va shu parol bilan tizimga kiradi.',
    accountPassword: 'Bemor uchun parol',
    caregiverSection: 'Bemorning yaqin kishisi',
    addCaregiver: 'Yaqin kishini biriktirish',
    caregiverName: 'Yaqin kishining ismi',
    caregiverPhone: 'Yaqin kishining telefoni',
    caregiverRelation: 'Qarindoshligi',
    caregiverPassword: 'Yaqin kishi uchun parol',
    caregiverPermissions: 'Yaqin kishiga ruxsat berilgan ma’lumotlar',
    caregiverPermissionsHint:
      'Yaqin kishi faqat siz belgilagan ma’lumotlarni ko‘radi. Barcha tibbiy ma’lumotlar avtomatik ochilmaydi.',

    diabetesTypeLabel: 'Diabet turi',
    diagnosisDate: 'Tashxis sanasi',
    hba1c: 'HbA1c (%)',
    recentHospitalization: 'Yaqinda shifoxonaga yotqizilganmi?',
    priorHypoglycemia: 'Oldingi gipoglikemiya holatlari',
    clinicalNotes: 'Muhim klinik izohlar',
    cgm: 'Uzluksiz glyukoza monitoringi (CGM)',
    cgmOff: 'Ishlatilmaydi',
    cgmOn: 'Ishlatiladi',
    cgmPlanned:
      'CGM qurilmalari bilan integratsiya keyingi bosqichda rejalashtirilgan. Hozircha o‘lchovlar qo‘lda kiritiladi.',
    diagnosisNote:
      'Tashxis va klinik ma’lumotlarni faqat tibbiyot xodimi kiritadi. Tizim tashxis qo‘ymaydi.',

    medicationName: 'Dori nomi',
    dose: 'Doza',
    unit: 'Birlik',
    dosesPerDay: 'Kuniga necha marta',
    scheduleType: 'Qabul qilish vaqti',
    exactTimes: 'Eslatma vaqtlari',
    exactTimesHint:
      '“Ertalab” — bu qabul qilish turi. Eslatma yuboriladigan aniq vaqtni quyida belgilang.',
    customTimes: 'Aniq vaqtni belgilash',
    addTime: 'Vaqt qo‘shish',
    startDate: 'Boshlanish sanasi',
    endDate: 'Tugash sanasi',
    priority: 'Muhimlik darajasi',
    medicationNote: 'Izoh',
    addMedication: 'Dori qo‘shish',
    noMedications: 'Hozircha dori qo‘shilmagan.',
    medicationsHint:
      'Muhimlik darajasini tibbiyot xodimi belgilaydi. Tizim buni o‘zi aniqlamaydi.',

    monitoringHint:
      'Har bir bemor uchun kuzatuv alohida sozlanadi. Barcha bemorlar hamma o‘lchovni bajarishi shart emas.',
    monitoringGlucose: 'Glyukoza',
    monitoringBp: 'Qon bosimi',
    monitoringSymptom: 'Belgilar / simptomlar',
    monitoringMedication: 'Dori qabul qilish',
    monitoringMedicationNote: 'Dori qabul qilish jadval asosida avtomatik kuzatiladi.',
    frequency: 'Kuniga necha marta',
    measurementTimes: "O'lchov vaqtlari",
    contextLabel: 'Holati',

    remindersTitle: 'Eslatma va eskalatsiya sozlamalari',
    remindersHint:
      'Bu qiymatlarni tibbiyot xodimi belgilaydi. Tizim ularni o‘zi o‘zgartirmaydi.',
    repeatMinutes: 'Takroriy eslatma oralig‘i (daqiqa)',
    maxReminders: 'Eslatmalar soni',
    snoozeMinutes: '“Kechroq” oralig‘i (daqiqa)',
    escalateNormal: 'Oddiy dori uchun eskalatsiya (daqiqa)',
    escalateImportant: 'Muhim dori uchun eskalatsiya (daqiqa)',
    escalateCritical: 'Juda muhim dori uchun eskalatsiya (daqiqa)',

    thresholdsTitle: 'Klinik chegaralar',
    thresholdsHint:
      'Chegaralar umumiy tibbiy qoida emas — ularni har bir bemor uchun tibbiyot xodimi tasdiqlaydi.',

    submit: "Ro'yxatdan o'tkazish va rejani tasdiqlash",
    submitting: 'Saqlanmoqda...',
    successTitle: 'Bemor ro‘yxatdan o‘tkazildi',
    successBody: 'Davolash va kuzatuv rejasi tasdiqlandi va faollashtirildi.',
    goToPatient: 'Bemor kartasini ochish',
    registerAnother: 'Yana bemor qo‘shish',
    requiredHint: '* bilan belgilangan maydonlar to‘ldirilishi shart.',
  },

  schedule: {
    morning: 'Ertalab',
    morning_noon: 'Ertalab va tushda',
    morning_evening: 'Ertalab va kechqurun',
    noon: 'Tushda',
    noon_evening: 'Tushda va kechqurun',
    evening: 'Kechqurun',
    bedtime: 'Uxlashdan oldin',
    every_8h: 'Har 8 soatda',
    every_12h: 'Har 12 soatda',
    as_needed: "Zarurat bo'lganda",
    custom: 'Aniq vaqtni belgilash',
  },

  priority: {
    normal: 'Oddiy',
    important: 'Muhim',
    critical: 'Juda muhim',
  },

  units: {
    mg: 'mg',
    ml: 'ml',
    unit: 'birlik',
    tablet: 'tabletka',
    drop: 'tomchi',
  },

  ai: {
    label: 'AI tavsiyasi',
    title: 'AI tavsiyasi',
    subtitle: 'Kuzatuv rejasi bo‘yicha taklif',
    generate: 'AI tavsiyasini olish',
    generating: 'Tavsiya tayyorlanmoqda...',
    accept: 'Qabul qilish / tasdiqlash',
    modify: "O'zgartirish",
    reject: 'Rad etish',
    accepted: 'AI tavsiyasi qabul qilindi',
    rejected: 'AI tavsiyasi rad etildi',
    reasons: 'Nima uchun shunday taklif qilindi',
    approvedPlan: 'Tasdiqlangan klinik reja',
    approvedPlanHint:
      'Faqat tibbiyot xodimi tasdiqlagan reja bemorga yuboriladi. AI tavsiyasi o‘zi faollashmaydi.',
    summaryTitle: 'AI tahlili',
    summaryGenerate: 'Tahlilni yangilash',
    noSummary: 'Hozircha AI tahlili yaratilmagan.',
    reviewed: 'Ko‘rib chiqildi',
    disclaimerShort: 'AI tavsiyasi — yakuniy qaror tibbiyot xodimiga tegishli.',
  },

  carePlan: {
    title: 'Davolash va kuzatuv rejasi',
    listTitle: 'Davolash rejalari',
    version: 'Versiya',
    status: 'Holat',
    draft: 'Loyiha',
    active: 'Faol',
    archived: 'Arxivlangan',
    approvedBy: 'Tasdiqlagan xodim',
    approvedAt: 'Tasdiqlangan vaqt',
    notApproved: 'Tasdiqlanmagan',
    startDate: 'Boshlanish sanasi',
    endDate: 'Tugash sanasi',
    medications: 'Dorilar',
    monitoring: 'Kuzatuv',
    history: 'Reja tarixi',
    noPlan: 'Faol davolash rejasi yo‘q.',
    approve: 'Rejani tasdiqlash',
    newVersion: 'Yangi versiya yaratish',
    versionNote:
      'Reja o‘zgartirilganda eski versiya o‘chirilmaydi — yangi versiya yaratiladi va tarix saqlanadi.',
    thresholds: 'Klinik chegaralar',
    reminders: 'Eslatmalar',
    noMedications: 'Rejada dori belgilanmagan.',
  },

  alerts: {
    title: 'Ogohlantirishlar',
    centerTitle: 'Ogohlantirishlar markazi',
    filters: {
      all: 'Barchasi',
      urgent: 'Shoshilinch',
      warning: "E'tibor kerak",
      closed: 'Yopilgan',
      open: 'Ochiq',
    },
    columns: {
      patient: 'Bemor',
      reason: 'Sabab',
      created: 'Vaqt',
      severity: 'Muhimlik',
      assigned: 'Mas’ul hamshira',
      status: 'Holat',
      action: 'Amal',
    },
    state: {
      new: 'Yangi',
      in_review: "Ko'rib chiqilmoqda",
      contacted: 'Bog‘lanildi',
      closed: 'Yopildi',
    },
    empty: 'Ogohlantirishlar yo‘q.',
    review: "Ko'rib chiqish",
    take: 'Ishga olish',
    markContacted: 'Bog‘lanildi deb belgilash',
    close: 'Yopish',
    notes: 'Ichki izohlar',
    addNote: 'Izoh qo‘shish',
    notePlaceholder: 'Bemor bilan nima qilinganini yozing...',
    noNotes: 'Izohlar yo‘q.',
    assignToMe: 'O‘zimga biriktirish',
    elapsed: 'O‘tgan vaqt',
    detailsTitle: 'Ogohlantirish tafsilotlari',
    contact: 'Bemor telefoni',
    emergencyContact: 'Favqulodda aloqa',
    safetyNote:
      'Tizim bemorga qo‘shimcha doza qabul qilishni taklif qilmaydi va dozani o‘zgartirmaydi. Qaror tibbiyot xodimiga tegishli.',
    closeConfirmTitle: 'Ogohlantirishni yopish',
    closeConfirmBody: 'Ogohlantirishni yopishni tasdiqlaysizmi? U yopilganlar ro‘yxatiga o‘tadi.',
  },

  reports: {
    title: 'Hisobotlar',
    period: 'Davr',
    d7: '7 kun',
    d14: '14 kun',
    d30: '30 kun',
    choosePatient: 'Bemorni tanlang',
    adherence: 'Davolashga rioya qilish',
    adherenceByDay: 'Kunlar bo‘yicha dori qabul qilish',
    glucoseEntries: 'Glyukoza o‘lchovlari',
    bpEntries: 'Qon bosimi o‘lchovlari',
    symptomReports: 'Belgilar haqida xabarlar',
    alertsCount: 'Ogohlantirishlar',
    average: 'O‘rtacha',
    min: 'Eng past',
    max: 'Eng yuqori',
    taken: 'Qabul qilingan',
    missed: 'O‘tkazib yuborilgan',
    pending: 'Kutilmoqda',
    noData: 'Tanlangan davrda ma’lumot yo‘q.',
    total: 'Jami',
  },

  patientHome: {
    title: 'Bugungi reja',
    greeting: 'Assalomu alaykum',
    allDone: 'Bugungi reja to‘liq bajarildi. Rahmat!',
    nothingToday: 'Bugun uchun vazifa belgilanmagan.',
    taken: 'Qabul qilindi',
    take: 'Qabul qildim',
    later: 'Kechroq',
    waiting: 'Kutilmoqda',
    missed: 'Bajarilmadi',
    done: 'Bajarildi',
    enterMeasurement: "O'lchovni kiritish",
    measureGlucose: 'Glyukozani o‘lchang',
    measureBp: 'Qon bosimini o‘lchang',
    symptomCheck: 'Holatingizni belgilang',
    progress: (done: number, total: number) => `${done} / ${total} bajarildi`,
    snoozed: (time: string) => `${time} da eslatiladi`,
    noPlanTitle: 'Sizga hali davolash rejasi tayinlanmagan',
    noPlanBody: 'Shifoxona rejani tasdiqlagach, u shu yerda ko‘rinadi.',
    remindersTitle: 'Eslatmalar',
    enableNotifications: 'Brauzer eslatmalarini yoqish',
    notificationsOn: 'Brauzer eslatmalari yoqilgan',
  },

  medications: {
    title: 'Dorilarim',
    schedule: 'Qabul qilish jadvali',
    history: 'Oxirgi qabul qilishlar',
    noHistory: 'Hozircha yozuvlar yo‘q.',
    priorityLabel: 'Muhimlik',
    everyDayAt: 'Har kuni',
    doseTaken: 'Qabul qilindi',
    doseMissed: 'Tasdiqlanmadi',
    dosePending: 'Kutilmoqda',
    doseSnoozed: 'Keyinga qoldirildi',
  },

  measurements: {
    title: "O'lchovlarim",
    glucose: 'Glyukoza',
    bloodPressure: 'Qon bosimi',
    symptoms: 'Belgilar',
    addGlucose: 'Glyukoza o‘lchovini kiritish',
    addBp: 'Qon bosimini kiritish',
    addSymptom: 'Holatni belgilash',
    glucoseValue: 'Glyukoza qiymati (mg/dL)',
    measuredAt: 'O‘lchangan vaqt',
    contextLabel: 'Holati',
    systolic: 'Sistolik bosim',
    diastolic: 'Diastolik bosim',
    pulse: 'Yurak urish tezligi',
    noReadings: 'Hozircha o‘lchovlar kiritilmagan.',
    savedGlucose: 'Glyukoza o‘lchovi saqlandi.',
    savedBp: 'Qon bosimi o‘lchovi saqlandi.',
    savedSymptom: 'Holatingiz saqlandi.',
    alertRaised: 'Ko‘rsatkich belgilangan chegaradan chiqdi. Hamshiraga xabar berildi.',
    manualNote:
      'O‘lchovlar qo‘lda kiritiladi. Tizimning o‘zi glyukoza yoki qon bosimini o‘lchamaydi.',
    context: {
      fasting: 'Och qoringa',
      before_meal: 'Ovqatdan oldin',
      after_meal: 'Ovqatdan keyin',
      bedtime: 'Uxlashdan oldin',
      any: 'Belgilanmagan',
    },
  },

  symptoms: {
    question: 'Bugun o‘zingizni qanday his qilyapsiz?',
    good: 'Yaxshi',
    not_good: 'Unchalik yaxshi emas',
    bad: 'Yomon',
    chooseSymptoms: 'Qanday belgilar bor? (bir nechtasini tanlash mumkin)',
    list: {
      thirst: 'Kuchli chanqash',
      urination: 'Tez-tez siyish',
      dizziness: 'Bosh aylanishi',
      weakness: 'Kuchli holsizlik',
      nausea: 'Ko‘ngil aynishi yoki qusish',
      tremor: 'Titrash',
      sweating: 'Terlash',
      confusion: 'Chalkashlik',
      other: 'Boshqa',
    },
    noteLabel: 'Qo‘shimcha izoh',
    submit: 'Yuborish',
    safetyNote:
      'Bu so‘rov tashxis qo‘ymaydi. Javobingiz kuzatuv uchun hamshiraga yetkaziladi. Holatingiz keskin yomonlashsa, tez tibbiy yordamga murojaat qiling.',
  },

  notifications: {
    title: 'Ogohlantirishlar',
    empty: 'Yangi xabarlar yo‘q.',
    markAllRead: 'Barchasini o‘qilgan deb belgilash',
    unread: 'o‘qilmagan',
  },

  assistant: {
    title: 'Hamshira AI',
    subtitle: 'Yozuvlaringiz asosida savollaringizga javob beradi.',
    placeholder: 'Savolingizni yozing...',
    send: 'Yuborish',
    sending: 'Yuborilmoqda...',
    intro:
      'Men sizning o\u2018lchovlaringiz va dori jadvalingiz asosida javob beraman. Tashxis qo\u2018ymayman va doza tayinlamayman.',
    disclaimer: 'Shifora tashxis qo\u2018ymaydi va dori tayinlamaydi.',
    refusal: 'Men bu savolingizga javob bera olmayman. Iltimos, hamshira yoki shifokor javobini kuting.',
    queued: 'Savolingiz tibbiyot xodimiga yuborildi.',
    waitingStatus: 'Holat: Javob kutilmoqda',
    sources: 'Manbalar',
    myQuestions: 'Savollarim',
    noQuestions: 'Hozircha savol yubormagansiz.',
    answeredBy: 'Javob berdi',
    online: 'Onlayn',
    open: 'Hamshira AI bilan suhbat',
    typing: 'Yozmoqda',
    usageTitle: 'Bugungi foydalanish',
    voiceLabel: 'Ovoz',
    imageLabel: 'Rasm',
    voiceNote: 'Ovozli xabar',
    photo: 'Rasm',
    recordVoice: 'Ovozli xabar yozish',
    sendPhoto: 'Rasm yuborish',
    voiceLimit: 'Bugungi ovozli xabar limiti tugadi. Iltimos matn orqali yozing.',
    imageLimit: 'Bugungi rasm yuborish limiti tugadi.',
    micDenied: 'Mikrofonga ruxsat berilmadi.',
    staffSource: 'Shifoxona',
    planSource: 'Davolash rejasi',
    examples: [
      'Qandim oxirgi kunlarda qanday bo\u2018lyapti?',
      'Oxirgi haftada yaxshilandimmi?',
      'Bugungi ko\u2018rsatkichim oldingilariga qaraganda qanday?',
    ],
    emergencyTitle: 'Shoshilinch',
  },

  trend: {
    title: 'Qand darajasi dinamikasi',
    last7: 'Oxirgi 7 kun',
    last30: 'Oxirgi 30 kun',
    readings: 'o\u2018lchovlar',
    average: 'O\u2018rtacha',
    min: 'Eng past',
    max: 'Eng yuqori',
    fasting: 'Ochlikda',
    postMeal: 'Ovqatdan keyin',
    inRange: 'Chegara ichida',
    change: 'O\u2018zgarish',
    noRange:
      'Shifokor maqsadli chegarani belgilamagani uchun \u201cchegara ichida\u201d ko\u2018rsatkichi hisoblanmaydi.',
    noData: 'Hali o\u2018lchov kiritilmagan.',
    rangeSource: 'Chegara manbasi',
  },

  questions: {
    title: 'Javobsiz savollar',
    subtitle: 'Hamshira AI javob bera olmagan savollar shu yerga tushadi.',
    empty: 'Javobsiz savollar yo\u2018q.',
    patient: 'Bemor',
    question: 'Savol',
    askedAt: 'Yuborilgan',
    priority: 'Muhimlik',
    status: 'Holat',
    assignedTo: 'Mas\u2019ul',
    unassigned: 'Biriktirilmagan',
    refusalReason: 'Rad etish sababi',
    retrievedSources: 'Topilgan manbalar',
    noSources: 'Tasdiqlangan manba topilmadi.',
    answerLabel: 'Javobingiz',
    answerPlaceholder: 'Bemorga javobingizni yozing...',
    submitAnswer: 'Javobni yuborish',
    assignToMe: 'O\u2018zimga biriktirish',
    close: 'Yopish',
    internalNotes: 'Ichki izohlar',
    addNote: 'Izoh qo\u2018shish',
    notePlaceholder: 'Faqat xodimlar ko\u2018radi...',
    context: 'Bemor ma\u2019lumoti',
    medications: 'Joriy dorilar',
    answeredNote: 'Javobingiz bemorga ko\u2018rinadi.',
    statuses: {
      unanswered: 'Javob kutilmoqda',
      assigned: 'Biriktirilgan',
      answered: 'Javob berilgan',
      closed: 'Yopilgan',
    },
    priorities: {
      normal: 'Oddiy',
      high: 'Muhim',
      urgent: 'Shoshilinch',
    },
    refusalReasons: {
      no_approved_source: 'Tasdiqlangan manba topilmadi',
      insufficient_information: 'Ma\u2019lumot yetarli emas',
      diagnosis_request: 'Tashxis so\u2018ralgan',
      medication_change_request: 'Doza o\u2018zgartirish so\u2018ralgan',
      missing_patient_data: 'Bemor ma\u2019lumoti yetishmaydi',
      retrieval_below_threshold: 'Manba ishonchliligi past',
      requires_clinician_judgement: 'Shifokor qarori kerak',
      conflicting_guidance: 'Manbalar bir-biriga zid',
      emergency_protocol: 'Shoshilinch protokol',
    },
  },

  caregiver: {
    title: 'Yaqiningiz holati',
    profileTitle: 'Profil',
    account: 'Hisobingiz',
    watchedPatients: 'Siz kuzatayotgan bemorlar',
    permissionsNote: 'Har bir bemor uchun qaysi ma\u2018lumotni ko\u2018rishingiz shifoxona tomonidan belgilanadi.',
    todayMedications: 'Bugungi dori qabul qilish',
    todayPlan: 'Bugungi reja',
    planDone: 'Bajarildi',
    planInProgress: 'Davom etmoqda',
    adherence7d: '7 kunlik dori qabul qilish',
    contactPatient: 'Bemor bilan bog‘lanish',
    contactNurse: 'Hamshiraga murojaat',
    contactNurseTitle: 'Hamshiraga murojaat',
    contactNurseBody: 'Xabaringiz hamshiraga yuboriladi va u ko‘rib chiqadi.',
    messageLabel: 'Xabar',
    messagePlaceholder: 'Nima haqida xabar bermoqchisiz?',
    send: 'Yuborish',
    sent: 'Murojaatingiz yuborildi. Hamshira ko‘rib chiqadi.',
    noAccess: 'Bu ma’lumotni ko‘rish huquqi berilmagan.',
    accessNote:
      'Siz faqat bemor yoki shifoxona ruxsat bergan ma’lumotlarni ko‘rasiz.',
    noPatients: 'Sizga hali biror bemor biriktirilmagan.',
    care: 'Parvarish',
    careHint: 'Bugun nima qilish kerakligi shu yerda ko‘rinadi.',
    importantProblem: 'Muhim dori qabul qilingani tasdiqlanmadi.',
  },

  profile: {
    title: 'Profil',
    personal: 'Shaxsiy ma’lumotlar',
    fullName: 'F.I.Sh.',
    birthDate: 'Tug‘ilgan sana',
    phone: 'Telefon',
    address: 'Manzil',
    hospital: 'Shifoxona',
    diabetesInfo: 'Diabet haqida',
    diagnosisDate: 'Tashxis sanasi',
    caregivers: 'Yaqin kishilar',
    noCaregivers: 'Biriktirilgan yaqin kishi yo‘q.',
    emergencyContact: 'Favqulodda aloqa',
    carePlanVersion: 'Amaldagi reja versiyasi',
  },

  patientProfile: {
    title: 'Bemor kartasi',
    personal: 'Shaxsiy ma’lumotlar',
    diabetes: 'Diabet haqida',
    activePlan: 'Faol davolash rejasi',
    medications: 'Dorilar',
    monitoringSchedule: 'Kuzatuv jadvali',
    recentMeasurements: 'So‘nggi o‘lchovlar',
    alerts: 'Ogohlantirishlar',
    caregivers: 'Yaqin kishilar',
    planHistory: 'Reja tarixi',
    todayPlan: 'Bugungi reja',
    adherence7: '7 kunlik rioya qilish',
    adherence30: '30 kunlik rioya qilish',
    lastActivity: 'So‘nggi faollik',
    openReport: 'Hisobotni ochish',
    noAlerts: 'Ogohlantirishlar yo‘q.',
    permissions: 'Ruxsatlar',
    hba1c: 'HbA1c',
    clinicalNotes: 'Klinik izohlar',
  },

  permissions: {
    view_today_plan: 'Bugungi reja',
    view_adherence: 'Dori qabul qilish darajasi',
    view_alerts: 'Ogohlantirishlar',
    view_measurements: 'O‘lchovlar',
    view_care_plan: 'Davolash rejasi',
    view_clinical_notes: 'Klinik izohlar',
  },

  validation: {
    required: 'Bu maydon to‘ldirilishi shart.',
    checkFields: 'Iltimos, quyidagi maydonlarni tekshiring.',
  },
} as const

export type ScheduleKey = keyof typeof uz.schedule
export type PriorityKey = keyof typeof uz.priority
export type StatusKey = keyof typeof uz.status
